apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  username: cm9vdA==
  password: RG9scGhpbjgx
  google_client_id: NTMwODk4NDY2MDA4LWozcDEwa2QzcHZtNTlwa2Y3c3JtbWE1bXVjNmszc2xjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  google_client_secret: blhmTWtybGFpYWJ3eUFJTkhxR1h6X0df
