apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  username: cm9vdA==
  password: RG9scGhpbjgx
  google_client_id: MTQ3ODQyMjQzOTk5LXIzNDkwbTFzYWFuc3VlMzJpMGl1YnVzbW85OWI0bnEzLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  google_client_secret: aDRtX2pRUElsdElZbW1ZZnpvVFhwd1pj 
  rails_master_key: ZDY2OTUyY2M4MDdhOTNiOTQ2YTNhNjA5NjRkZTgwOWM=
